/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 jordan.glb 
Author: Joe-Wall (https://sketchfab.com/joewall)
License: SKETCHFAB Editorial (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/air-jordan-1-variety-pack-feabb5d8f896497d8def5076ebe220bb
Title: Air Jordan 1 Variety Pack
*/

// import { useGLTF, Stage, PresentationControls } from '@react-three/drei'
// import { useRef } from "react";

// const Jordan = (props) => {
//   const group = useRef();
//   const { nodes, materials } = useGLTF('/jordan.glb')
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group ref={group} rotation={[-Math.PI / 2, 0, 0]}>
//         <mesh geometry={nodes.Object_2.geometry} material={materials.Jordan1_LowPoly_BnW} dispose={null}/>
//         <mesh geometry={nodes.Object_3.geometry} material={materials.Jordan1_LowPoly_Chicagp} />
//         <mesh geometry={nodes.Object_4.geometry} material={materials.Jordan1_LowPoly_Obsidian} />
//         <mesh geometry={nodes.Object_5.geometry} material={materials.Jordan1_LowPoly_SBB} />
//         <mesh geometry={nodes.Object_6.geometry} material={materials.Jordan1_LowPoly_UniBLue} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/jordan.glb')

// export default Jordan

import { Canvas } from "@react-three/fiber";
import { useGLTF, Stage, PresentationControls } from '@react-three/drei';

const Model = () => {
  const { nodes, materials } = useGLTF('/jordan.glb')
  const shoeArray = [
    {
      name: "jordan1BnW",
      geometry: nodes.Object_2.geometry,
      material: materials.Jordan1_LowPoly_BnW
    },
    {
      name: "jordan1Chg",
      geometry: nodes.Object_3.geometry,
      material: materials.Jordan1_LowPoly_Chicagp
    },
    {
      name: "jordan1Obs",
      geometry: nodes.Object_4.geometry,
      material: materials.Jordan1_LowPoly_Obsidian
    },
    {
      name: "jordan1Sbb",
      geometry: nodes.Object_5.geometry,
      material: materials.Jordan1_LowPoly_SBB
    },
    {
      name: "jordan1Uni",
      geometry: nodes.Object_6.geometry,
      material: materials.Jordan1_LowPoly_UniBLue
    },
  ]

  let shoeComponent = shoeArray.map((shoeObject) => {
    return (
      <mesh onClick={() => console.log(`${shoeObject.name}`)} key={shoeObject.name} position={[0,0,0]} rotation={[-Math.PI / 2, 0.02, 0]} polar={[0,0, Math.PI / 4]} geometry={shoeObject.geometry} material={shoeObject.material}/>
      )
  })
  return shoeComponent; 
}


const Jordan = (props) => {
  return (
    <Canvas dpr={[1, 2]} camera={{ fov: 100 }}>
      <PresentationControls speed={1.5} zoom={1}>
        <Stage environment={null}>
          <Model />
        </Stage>
      </PresentationControls>
    </Canvas>
  )
}

useGLTF.preload('/jordan.glb')

export default Jordan

  // let shoeObject = for (const shoe in shoeObject) {
  //   return(
  //     <group dispose={null} rotation={[-Math.PI / 2, 0.02, 0]}>
  //             <mesh geometry={shoeObject[shoe].geometry} material={shoeObject[shoe].material} />
  //     </group>
  //   )
  // }
  // return(
  //   <group {...props} dispose={null} rotation={[-Math.PI / 2, 0.02, 0]}>
  //          <mesh geometry={shoeObject.jordan1BnW.geometry} material={materials.Jordan1_LowPoly_BnW} />
  //          <mesh geometry={shoeObject.jordan1Chg.geometry} material={materials.Jordan1_LowPoly_Chicagp} />
  //          <mesh geometry={nodes.Object_4.geometry} material={materials.Jordan1_LowPoly_Obsidian} />
  //          <mesh geometry={nodes.Object_5.geometry} material={materials.Jordan1_LowPoly_SBB} />
  //          <mesh geometry={nodes.Object_6.geometry} material={materials.Jordan1_LowPoly_UniBLue} />
  //     </group>
  // )